## Notes 
1. Tensors are multi dimensional arrays 
2. an array is an ordered arrangement of numbers


In [2]:
import tensorflow as tf

## tf.constant( list )
- Used to create tensors, the argument is list 

In [3]:
# one_dim_tesnor  = tf.constant([])    # this is also valid 
# 
one_dim_tesnor  = tf.constant([6])    # 
print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)

tf.Tensor([6], shape=(1,), dtype=int32)
(1,)
<dtype: 'int32'>


In [4]:
one_dim_tesnor  = tf.constant([3.14])    # 
print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)

tf.Tensor([3.14], shape=(1,), dtype=float32)
(1,)
<dtype: 'float32'>


    - Tensor.shape tells you the size of the tesor along each axes 
    - Tesnor.dtype tells you the type of all the elements in the tensor

In [5]:
one_dim_tesnor  = tf.constant([6,7,1])    # 
print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)

tf.Tensor([6 7 1], shape=(3,), dtype=int32)
(3,)
<dtype: 'int32'>


In [6]:
one_dim_tesnor  = tf.constant([6,3.17,1])    # 
print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)

tf.Tensor([6.   3.17 1.  ], shape=(3,), dtype=float32)
(3,)
<dtype: 'float32'>


## Error:
    - The below code will  give an error 
    - Can't convert Python sequence with mixed types to Tensor.

In [7]:
# one_dim_tesnor  = tf.constant([6,"hello",1])    # Insode a tensor string are not allowd 
# print(one_dim_tesnor)
# print(one_dim_tesnor.shape)
# print(one_dim_tesnor.dtype)

In [8]:
one_dim_tesnor  = tf.constant([6,True,1])    # 
print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)

tf.Tensor([6 1 1], shape=(3,), dtype=int32)
(3,)
<dtype: 'int32'>


In [9]:
one_dim_tesnor  = tf.constant([6,False,1])    # 
print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)

tf.Tensor([6 0 1], shape=(3,), dtype=int32)
(3,)
<dtype: 'int32'>


In [10]:
two_dim_tensor = tf.constant([
    [1,5,7],
    [7,8,5]
])

print(two_dim_tensor)
print("The tensor shape is ",two_dim_tensor.shape)
print("The tenor data type is ",two_dim_tensor.dtype)
print("The tensor dimension is: ",two_dim_tensor.ndim)

tf.Tensor(
[[1 5 7]
 [7 8 5]], shape=(2, 3), dtype=int32)
The tensor shape is  (2, 3)
The tenor data type is  <dtype: 'int32'>
The tensor dimension is:  2


In [11]:
three_dim_tensor = tf.constant([
    [
       [1,5,7],
       [7,8,5] 
    ],
    [
       [1,5,8],
       [9,8,6] 
    ],
    [
       [1,3,7],
       [7,4,5] 
    ]   
])

print(three_dim_tensor)
print("The tensor shape is : ",three_dim_tensor.shape)
print("The tensor data type is: ",three_dim_tensor.dtype)
print("The tensor dimensio is: ",three_dim_tensor.ndim)

tf.Tensor(
[[[1 5 7]
  [7 8 5]]

 [[1 5 8]
  [9 8 6]]

 [[1 3 7]
  [7 4 5]]], shape=(3, 2, 3), dtype=int32)
The tensor shape is :  (3, 2, 3)
The tensor data type is:  <dtype: 'int32'>
The tensor dimensio is:  3


In [12]:
three_dim_tensor = tf.constant([
   [ [
       [1,5,7],
       [7,8,5] 
    ],
    [
       [1,5,8],
       [9,8,6] 
    ],
    [
       [1,3,7],
       [7,4,5] 
    ]   ],

   [ [
       [10,5,7],
       [7,80,5] 
    ],
    [
       [1,5,8],
       [9,80,60] 
    ],
    [
       [1,30,7],
       [70,4,5] 
    ]   ]
])

print(three_dim_tensor)
print("The tensor shape is : ",three_dim_tensor.shape)
print("The tensor data type is: ",three_dim_tensor.dtype)
print("The tensor dimension is: ",three_dim_tensor.ndim)

tf.Tensor(
[[[[ 1  5  7]
   [ 7  8  5]]

  [[ 1  5  8]
   [ 9  8  6]]

  [[ 1  3  7]
   [ 7  4  5]]]


 [[[10  5  7]
   [ 7 80  5]]

  [[ 1  5  8]
   [ 9 80 60]]

  [[ 1 30  7]
   [70  4  5]]]], shape=(2, 3, 2, 3), dtype=int32)
The tensor shape is :  (2, 3, 2, 3)
The tensor data type is:  <dtype: 'int32'>
The tensor dimension is:  4


## NOTE : keep eyes on comma otherwise will get an error 

In [13]:
# We can give our own datatypes to a tensor variables
two_dim_tensor = tf.constant([
    [1,5,7],
    [7,8,5]
],dtype = tf.float32)

print(two_dim_tensor)
print("The tensor shape is ",two_dim_tensor.shape)
print("The tenor data type is ",two_dim_tensor.dtype)
print("The tensor dimension is: ",two_dim_tensor.ndim)


# Although the data types of vaues are integer but the tensor variable is of float type 
# at the end of every value will get an decimal '.' as we can see in below example

tf.Tensor(
[[1. 5. 7.]
 [7. 8. 5.]], shape=(2, 3), dtype=float32)
The tensor shape is  (2, 3)
The tenor data type is  <dtype: 'float32'>
The tensor dimension is:  2


In [14]:
two_dim_tensor = tf.constant([
    [1,5,7],
    [7,8,5]
],dtype = tf.float16)                # it will take less memory because float32 is of more byte than float6 
 
print(two_dim_tensor)
print("The tensor shape is ",two_dim_tensor.shape)
print("The tenor data type is ",two_dim_tensor.dtype)
print("The tensor dimension is: ",two_dim_tensor.ndim)

tf.Tensor(
[[1. 5. 7.]
 [7. 8. 5.]], shape=(2, 3), dtype=float16)
The tensor shape is  (2, 3)
The tenor data type is  <dtype: 'float16'>
The tensor dimension is:  2


#### tenordata types:
- A Tensor or SparseTensor or IndexedSlices of numeric type. It could be uint8 , uint16 , uint32 , uint64 , int8 , int16 , int32 , int64 , float16 , float32 , float64 , complex64 , complex128 , bfloat16 . The destination type. The list of supported dtypes is the same as x

In [15]:
one_dim_tesnor  = tf.constant([6,7,1], dtype=tf.float32)    # we are allow to convert int values to float 
print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)

tf.Tensor([6. 7. 1.], shape=(3,), dtype=float32)
(3,)
<dtype: 'float32'>


In [16]:
# one_dim_tesnor  = tf.constant([6,3.14,1], dtype=tf.int32)    # we are nit allow to convert float values to interger 
# print(one_dim_tesnor)
# print(one_dim_tesnor.shape)
# print(one_dim_tesnor.dtype)

# Error : Cannot convert [6, 3.14, 1] to EagerTensor of dtype int32

In [17]:
# type casting in tensor flow
tesnor  = tf.constant([6,3.14,1], dtype=tf.float32)    # we are nit allow to convert float values to interger 

one_dim_tesnor = tf.cast(tesnor, dtype=tf.int16)   # this is how we perform type casting of tensors in tensorflow 

print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)

tf.Tensor([6 3 1], shape=(3,), dtype=int16)
(3,)
<dtype: 'int16'>


In [18]:
tesnor  = tf.constant([6,3.14,1], dtype=tf.float32)    # we are nit allow to convert float values to interger 

one_dim_tesnor = tf.cast(tesnor, dtype=tf.bool)   # this is how we perform type casting of tensors in tensorflow 

print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)
(3,)
<dtype: 'bool'>


In [19]:
tesnor  = tf.constant([-6,3.14,0], dtype=tf.float32)    # we are nit allow to convert float values to interger 

one_dim_tesnor = tf.cast(tesnor, dtype=tf.bool)   # this is how we perform type casting of tensors in tensorflow 

print(one_dim_tesnor)
print(one_dim_tesnor.shape)
print(one_dim_tesnor.dtype)


# bool data type 
# 0 - false
# other than 0 - True 

tf.Tensor([ True  True False], shape=(3,), dtype=bool)
(3,)
<dtype: 'bool'>


In [20]:
bool_tensor = tf.constant([True, False, True])
print(bool_tensor)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [21]:
bool_tensor = tf.constant([5, False, 7])
print(bool_tensor)

tf.Tensor([5 0 7], shape=(3,), dtype=int32)


In [22]:
string_tensor = tf.constant(["lets learn TensorFlow"])
print(string_tensor)

# This will not give an error

tf.Tensor([b'lets learn TensorFlow'], shape=(1,), dtype=string)


In [23]:
# string_tensor = tf.constant([8, "lets learn TensorFlow", 5])
# print(string_tensor)

# This will produce an error 

In [24]:
string_tensor = tf.constant(["Hello","hii","bye"])
print(string_tensor)

tf.Tensor([b'Hello' b'hii' b'bye'], shape=(3,), dtype=string)


## Converting Numpy array into tensors 

### tf.convert_to_tensor( numpy array ) 

In [25]:
import numpy as np

In [26]:
np_array = np.array([1,5,9,3,7])
np_tensor = tf.convert_to_tensor(np_array)
print(np_array)
print(np_array.shape)
print(np_array.dtype)

[1 5 9 3 7]
(5,)
int32


In [27]:
np_array = np.array([15, 5.5, 9.7, 3.14, 7])
np_tensor = tf.convert_to_tensor(np_array)
print(np_array)
print(np_array.shape)
print(np_array.dtype)

[15.    5.5   9.7   3.14  7.  ]
(5,)
float64


### tf.eye () method:
- method is used to create indentity matrix tensor of given dimension

In [28]:
# # complete signature of method is as follows 
# tf.eye(
#     num_rows,
#     num_columns=None,
#     batch_shape=None,
#     dtype=tf.dtypes.float32,
#     name=None
# )

# Note the default values aslo 

In [29]:
eye_tensor = tf.eye(2)

In [30]:
eye_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [31]:
print(eye_tensor)

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


In [32]:
## We can overide the tf.eye method aslo if we are not happy with the degault implementation of the method 
overriden_eye_tensor = tf.eye(
    num_rows = 4,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.int32,        # note this change
    name=None
)

In [33]:
print(overriden_eye_tensor)

tf.Tensor(
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]], shape=(4, 4), dtype=int32)


In [34]:
print(3 * overriden_eye_tensor)    # multiply 3

tf.Tensor(
[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]], shape=(4, 4), dtype=int32)


In [35]:
# if we dont define the number of columns then it is by default going to be square matrix 
# if we want our own number of clumns then we can do like

eye_tensor  = tf.eye(2, 4)       # 2-rowa and 4-columns
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]], shape=(2, 4), dtype=float32)


In [36]:
eye_tensor  = tf.eye(2, 4 ,  dtype = tf.bool)       # 2-rowa and 4-columns
print(eye_tensor)

tf.Tensor(
[[ True False False False]
 [False  True False False]], shape=(2, 4), dtype=bool)


In [37]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.bool,        # note this change
    name=None
)

print(eye_tensor)

tf.Tensor(
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]], shape=(3, 5), dtype=bool)


In [38]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=5,
    batch_shape=[3],
    dtype=tf.dtypes.float32,        # note this change
    name=None
)

print("The complete tensor is: ",eye_tensor)
print("\nThe first tensor is: ",eye_tensor[0])
print("\nThe second tensor is: ",eye_tensor[1])
print("\nThe third tensor is: ",eye_tensor[2])

The complete tensor is:  tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]], shape=(3, 3, 5), dtype=float32)

The first tensor is:  tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)

The second tensor is:  tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)

The third tensor is:  tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)


### tf.fill () method 
- Creates a tensor filled with a scalar value.

In [39]:
# complete signature of methos is as follows 

# tf.fill(
#     dims, value, name=None
# )

In [40]:
tf.fill([2, 3], 9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [41]:
fill_tensor = tf.fill(
    dims = [3,5],
    value = 9,
    name = None
)

print(fill_tensor)

tf.Tensor(
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]], shape=(3, 5), dtype=int32)


In [42]:
fill_tensor = tf.fill(
    dims = [5,3,2],
    value = 9,
    name = None
)

print(fill_tensor)

tf.Tensor(
[[[9 9]
  [9 9]
  [9 9]]

 [[9 9]
  [9 9]
  [9 9]]

 [[9 9]
  [9 9]
  [9 9]]

 [[9 9]
  [9 9]
  [9 9]]

 [[9 9]
  [9 9]
  [9 9]]], shape=(5, 3, 2), dtype=int32)


### tf.ones () method
- Creates a tensor with all elements set to one (1).

In [43]:
tf.ones([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [44]:
fill_tensor = tf.ones(
    shape = [5,3,2],
    name = None
)

print(fill_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


### tf.ones_like()
- Creates a tensor of all ones that has the same shape as the input (Input is also an tensor)

In [45]:
temp_tensor = tf.constant([
    [1, 2, 3],
    [4, 0, 6]
])

print(temp_tensor)
print("\n\nOnes like tensor")
print(tf.ones_like(temp_tensor))

tf.Tensor(
[[1 2 3]
 [4 0 6]], shape=(2, 3), dtype=int32)


Ones like tensor
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


### tf.zeros() methos 
- Creates a tensor with all elements set to zero.

In [46]:
tf.zeros([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

### tf.shape() Method
- returns the shape of tensor

In [47]:
temp_tensor = tf.constant([
    [1, 2, 3],
    [4, 0, 6]
])

print(tf.shape(temp_tensor))

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [48]:
# clearly note the diference between tensor.idim and tensor.shape

print(temp_tensor.ndim)
print(temp_tensor.shape)

2
(2, 3)


In [49]:
tf.rank(temp_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### tf.size() method:
- Returns the size of a tensor.

In [52]:
temp_tensor = tf.constant([
    [
        [1, 1, 1], 
        [2, 2, 2]
    ],

    [
        [3, 3, 3], 
        [4, 4, 4]
    ]
])

tf.size(temp_tensor)   # see the numpy value 
# print(tf.size(temp_tensor))

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [53]:
tt = tf.constant([
    [1, 2, 3],
    [4, 0, 6]
])

print(tf.size(tt))

tf.Tensor(6, shape=(), dtype=int32)


### tf.random() methods

In [ ]:
# Complete signature of method is 

tf.random.normal(
    shape,
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

In [59]:
random_tensor = tf.random.normal(
    shape = [2,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[-1.5210497   1.0521117  -1.6889142 ]
 [-0.23752344 -0.48445648  0.97160536]], shape=(2, 3), dtype=float32)


In [62]:
random_normal_tensor = tf.random.normal(
    shape = [2,3],
    mean=5,
    stddev=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_normal_tensor) # tensor from normal distribution

tf.Tensor(
[[5.631578  5.766441  4.4511576]
 [5.909915  4.083678  3.6853127]], shape=(2, 3), dtype=float32)


In [63]:
# Uniform distribution 
random_uniform_tensor = tf.random.uniform(
    shape = [2,3],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_uniform_tensor)



tf.Tensor(
[[0.40113115 0.07538974 0.98595655]
 [0.404662   0.43271422 0.41230822]], shape=(2, 3), dtype=float32)


In [66]:
# Uniform distribution 
random_uniform_tensor = tf.random.uniform(
    shape = [5],
    minval=0,
    maxval=None,          # default max value is 1
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_uniform_tensor)

tf.Tensor([0.0166105  0.6527537  0.63461554 0.4780662  0.6517823 ], shape=(5,), dtype=float32)


In [69]:
# Uniform distribution 
random_uniform_tensor = tf.random.uniform(
    shape = [5],
    minval=0,
    maxval=10,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_uniform_tensor)

tf.Tensor([9.637825  5.560213  2.9522455 4.507022  0.9550154], shape=(5,), dtype=float32)


In [71]:
# # Uniform distribution 
# random_uniform_tensor = tf.random.uniform(
#     shape = [5],
#     minval=0,
#     maxval=None,          # default max value is 1
#     dtype=tf.dtypes.int32,
#     seed=None,
#     name=None
# )

# print(random_uniform_tensor)

# for int32 data type we need to mention the maxvalue otherwise we will get an error 
# # Error : Must specify maxval for integer dtype tf.int32

In [74]:
# Uniform distribution 
random_uniform_tensor = tf.random.uniform(
    shape = [5],
    minval=0,
    maxval=5,          # Note we are defining maxvalue hence will wont get error 
    dtype=tf.dtypes.int32, # data type is also int32
    seed=None,
    name=None
)

print(random_uniform_tensor)

tf.Tensor([1 3 1 4 4], shape=(5,), dtype=int32)


In [75]:
# Uniform distribution 
random_uniform_tensor = tf.random.uniform(
    shape = [5],
    minval=10,
    maxval=500,          # Note we are defining maxvalue hence will wont get error 
    dtype=tf.dtypes.int32, # data type is also int32
    seed=None,
    name=None
)

print(random_uniform_tensor)

tf.Tensor([327 116 286 252 192], shape=(5,), dtype=int32)


### seed parameter 

In [80]:
tf.random.set_seed(5)  # important to do this otherwise we will get different otputs each time 

print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [82]:
tf.random.set_seed(5)  # important to do this otherwise we will get different otputs each time 

print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [89]:
tf.random.set_seed(50)  # important to do this otherwise we will get different otputs each time 

print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([1 0 4], shape=(3,), dtype=int32)
tf.Tensor([0 2 0], shape=(3,), dtype=int32)
tf.Tensor([3 4 2], shape=(3,), dtype=int32)
tf.Tensor([1 3 2], shape=(3,), dtype=int32)


In [88]:
tf.random.set_seed(25)  # important to do this otherwise we will get different otputs each time 

print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=20))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=20))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=20))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=20))

tf.Tensor([3 2 0], shape=(3,), dtype=int32)
tf.Tensor([2 1 3], shape=(3,), dtype=int32)
tf.Tensor([4 1 0], shape=(3,), dtype=int32)
tf.Tensor([0 0 3], shape=(3,), dtype=int32)


## Indexing In tensors

In [98]:
temp_tensor = tf.constant([3,9,6,40,81,10,40,78,92,15,56])
print(temp_tensor)

tf.Tensor([ 3  9  6 40 81 10 40 78 92 15 56], shape=(11,), dtype=int32)


In [103]:
# to get first fp=our elements of tensors
print("The first element of tensor is : ",temp_tensor[0])
print("The first  4 elements of tensor is : ",temp_tensor[0:4])
print("Elements are : ",temp_tensor[1:5])   # we wants to go for 4th element then write 5 index
print("Elements are : ",temp_tensor[3:])   # everything after index 3
print("Elements are : ",temp_tensor[0:6:2])   # elements from index 0 to 5 by taking one jump
print("Elements are : ",temp_tensor[0:6:3])   # elements from index 0 to 5 by taking one jump
print("Elements are : ",temp_tensor[3:-2])



The first element of tensor is :  tf.Tensor(3, shape=(), dtype=int32)
The first  4 elements of tensor is :  tf.Tensor([ 3  9  6 40], shape=(4,), dtype=int32)
Elements are :  tf.Tensor([ 9  6 40 81], shape=(4,), dtype=int32)
Elements are :  tf.Tensor([40 81 10 40 78 92 15 56], shape=(8,), dtype=int32)
Elements are :  tf.Tensor([ 3  6 81], shape=(3,), dtype=int32)
Elements are :  tf.Tensor([ 3 40], shape=(2,), dtype=int32)
Elements are :  tf.Tensor([40 81 10 40 78 92], shape=(6,), dtype=int32)


In [105]:
## Note Two DImensional Tensors
two_D_tensor = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

print("Two dimensional arrays is : ",two_D_tensor)

Two dimensional arrays is :  tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [124]:
# convention followed is tensor[row,column]

# Accesing one row 
print("First row of tensor is  : ",two_D_tensor[0,])
print("secon row of tensor is  : ",two_D_tensor[1,])
print("third row of tensor is  : ",two_D_tensor[2,])
print("forth row of tensor is  : ",two_D_tensor[3,])

# accesing one element at a time 
print("first row, first element is   : ",two_D_tensor[0,0])  # oth row oth element
print("first row, second element is   : ",two_D_tensor[0,1])  # oth row 1st element
print("first row, third element is   : ",two_D_tensor[0,2])   # oth row 2nd element

# accesing one element at a time 
print("second row, first element is   : ",two_D_tensor[1,0])  # oth row oth element
print("second row, second element is   : ",two_D_tensor[1,1])  # oth row 1st element
print("second row, third element is   : ",two_D_tensor[1,2])   # oth row 2nd element

# accesing more than one elements at a time 
print("\n\n first two rows, first two elements : ",two_D_tensor[0:2, 0:2])  # first two rows, first two elements 
print("\n\n first three rows, first two elements : ",two_D_tensor[0:3, 0:2])  #
print("\n\n first three rows, 2nd and 3rd elements :",two_D_tensor[0:3, 1:3])  #


# 
print("All elements of first three rows : ", two_D_tensor[0:3, :])   
print("third row last two elements  : ", two_D_tensor[2, 1:])   


# accesing more than one elements at a time with jumping 
#print("\n\n first two rows, first two elements : ",two_D_tensor[0:4, 0:3, 2])  # first two rows, first two elements 

First row of tensor is  :  tf.Tensor([1 2 0], shape=(3,), dtype=int32)
secon row of tensor is  :  tf.Tensor([ 3  5 -1], shape=(3,), dtype=int32)
third row of tensor is  :  tf.Tensor([1 5 6], shape=(3,), dtype=int32)
forth row of tensor is  :  tf.Tensor([2 3 8], shape=(3,), dtype=int32)
first row, first element is   :  tf.Tensor(1, shape=(), dtype=int32)
first row, second element is   :  tf.Tensor(2, shape=(), dtype=int32)
first row, third element is   :  tf.Tensor(0, shape=(), dtype=int32)
second row, first element is   :  tf.Tensor(3, shape=(), dtype=int32)
second row, second element is   :  tf.Tensor(5, shape=(), dtype=int32)
second row, third element is   :  tf.Tensor(-1, shape=(), dtype=int32)


 first two rows, first two elements :  tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32)


 first three rows, first two elements :  tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


 first three rows, 2nd and 3rd elements : tf.Tensor(
[[ 2  0]
 [ 5 -1]
 [ 5  6]], shape=(3, 

In [128]:
print("Two dimensional tensor is : ", two_D_tensor)

Two dimensional tensor is :  tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [131]:
# Accesing elements column wise 
print("All elements of first columnn is : ",two_D_tensor[:,0])  
print("All elements of second columnn is : ",two_D_tensor[:,1])  
print("All elements of third columnn is : ",two_D_tensor[:,2]) 

# 
print("Second columns, third elements ", two_D_tensor[2,1])   # third row , second element  = two_D_tensor[2,1]


print(two_D_tensor[1:3, 0:2])




All elements of first columnn is :  tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)
All elements of second columnn is :  tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)
All elements of third columnn is :  tf.Tensor([ 0 -1  6  8], shape=(4,), dtype=int32)
Second columns, third elements  tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(
[[3 5]
 [1 5]], shape=(2, 2), dtype=int32)


## Accesing the elements of three dimenison tensor


In [132]:
three_D_tesnor = tf.constant([
    [
        [14,15,75],
        [8,9,7]
    ],
    [
        [66,78,90],
        [90,12,30]
    ],
    [

        [56,8,9],
        [80,50,10]
    ],
    [
        [15,20,14],
        [78,45,12]
    ]
])

print("Three dimensional tesnor is : ",three_D_tesnor)

Three dimensional tesnor is :  tf.Tensor(
[[[14 15 75]
  [ 8  9  7]]

 [[66 78 90]
  [90 12 30]]

 [[56  8  9]
  [80 50 10]]

 [[15 20 14]
  [78 45 12]]], shape=(4, 2, 3), dtype=int32)


In [135]:
# convension is [row,column,]
print("The first 2D tensor of 3D tensor", three_D_tesnor[0])
print("\n\nThe second 2D tensor of 3D tensor", three_D_tesnor[1])
print("\n\nThe third 2D tensor of 3D tensor", three_D_tesnor[2])
print("\n\nThe fourth 2D tensor of 3D tensor", three_D_tesnor[3])

The first 2D tensor of 3D tensor tf.Tensor(
[[14 15 75]
 [ 8  9  7]], shape=(2, 3), dtype=int32)


The second 2D tensor of 3D tensor tf.Tensor(
[[66 78 90]
 [90 12 30]], shape=(2, 3), dtype=int32)


The third 2D tensor of 3D tensor tf.Tensor(
[[56  8  9]
 [80 50 10]], shape=(2, 3), dtype=int32)


The fourth 2D tensor of 3D tensor tf.Tensor(
[[15 20 14]
 [78 45 12]], shape=(2, 3), dtype=int32)


In [137]:
#Accesing the entire 2D tensor 
print("All elements of first 2D tensor",three_D_tesnor[0, :,:])
print("\n\nAll elements of second 2D tensor",three_D_tesnor[1, :,:])
print("\n\nAll elements of third 2D tensor",three_D_tesnor[2, :,:])
print("\n\nAll elements of fourth 2D tensor",three_D_tesnor[3, :,:])

All elements of first 2D tensor tf.Tensor(
[[14 15 75]
 [ 8  9  7]], shape=(2, 3), dtype=int32)


All elements of second 2D tensor tf.Tensor(
[[66 78 90]
 [90 12 30]], shape=(2, 3), dtype=int32)


All elements of third 2D tensor tf.Tensor(
[[56  8  9]
 [80 50 10]], shape=(2, 3), dtype=int32)


All elements of fourth 2D tensor tf.Tensor(
[[15 20 14]
 [78 45 12]], shape=(2, 3), dtype=int32)


In [141]:
# Accesin the individual elements of any 2D tesnor of 3D tensor
print("First 2D tensors -> 2nd Row -> 2nd element :=>",three_D_tesnor[0,1,1])
print("First 2D tensors -> 1nd Row -> 2nd element :=>",three_D_tesnor[0,0,1])
print("First 2D tensors -> 1nd Row -> 1st element :=>",three_D_tesnor[0,0,0])

First 2D tensors -> 2nd Row -> 2nd element :=> tf.Tensor(9, shape=(), dtype=int32)
First 2D tensors -> 1nd Row -> 2nd element :=> tf.Tensor(15, shape=(), dtype=int32)
First 2D tensors -> 1nd Row -> 1st element :=> tf.Tensor(14, shape=(), dtype=int32)


In [144]:
# Accesin the individual elements of any 2D tesnor of 3D tensor
print("Third 2D tensors -> 2nd Row -> 2nd element :=>",three_D_tesnor[2,1,1])
print("Third 2D tensors -> 1st row -> all elements :=>",three_D_tesnor[2,0,:])
print("Third 2D tensors -> 2nd Row -> all elments :=>",three_D_tesnor[2,1,:])

Third 2D tensors -> 2nd Row -> 2nd element :=> tf.Tensor(50, shape=(), dtype=int32)
Third 2D tensors -> 1st row -> all elements :=> tf.Tensor([56  8  9], shape=(3,), dtype=int32)
Third 2D tensors -> 2nd Row -> all elments :=> tf.Tensor([80 50 10], shape=(3,), dtype=int32)


In [145]:
print("2nd and 3rd 2D tensors -> 1st row  -> all elemnts :=>",three_D_tesnor[1:3,0,:])

2nd and 3rd 2D tensors -> 1st row  -> all elemnts :=> tf.Tensor(
[[66 78 90]
 [56  8  9]], shape=(2, 3), dtype=int32)


In [146]:
print("2nd and 3rd 2D tensors -> 1st row  -> last two elemts :=>",three_D_tesnor[1:3,0,1:3])

2nd and 3rd 2D tensors -> 1st row  -> last two elemts :=> tf.Tensor(
[[78 90]
 [ 8  9]], shape=(2, 2), dtype=int32)


In [149]:
print("last 2D tensors -> 1st row  -> last two elemts :=>",three_D_tesnor[-1,0,-2:])

last 2D tensors -> 1st row  -> last two elemts :=> tf.Tensor([20 14], shape=(2,), dtype=int32)


In [150]:
print("Every 2D tensors last two columns",three_D_tesnor[:,:,1:3])

Every 2D tensors last two coumns tf.Tensor(
[[[15 75]
  [ 9  7]]

 [[78 90]
  [12 30]]

 [[ 8  9]
  [50 10]]

 [[20 14]
  [45 12]]], shape=(4, 2, 2), dtype=int32)


In [157]:
print(three_D_tesnor)

tf.Tensor(
[[[14 15 75]
  [ 8  9  7]]

 [[66 78 90]
  [90 12 30]]

 [[56  8  9]
  [80 50 10]]

 [[15 20 14]
  [78 45 12]]], shape=(4, 2, 3), dtype=int32)


In [154]:
print(three_D_tesnor[... , : , 2])      # Note

tf.Tensor(
[[75  7]
 [90 30]
 [ 9 10]
 [14 12]], shape=(4, 2), dtype=int32)


In [156]:
print(three_D_tesnor[... , : , 1]) # Note

tf.Tensor(
[[15  9]
 [78 12]
 [ 8 50]
 [20 45]], shape=(4, 2), dtype=int32)


In [158]:
print(three_D_tesnor[... , : , 0])

tf.Tensor(
[[14  8]
 [66 90]
 [56 80]
 [15 78]], shape=(4, 2), dtype=int32)


## Mathematicall Operation in Tensorflow