In [2]:
a = 5

In [3]:
import tensorflow as tf

In [4]:
x = tf.constant([5, -4 , 6])

In [5]:
abs_x = tf.math.abs(x)
print(abs_x)

tf.Tensor([5 4 6], shape=(3,), dtype=int32)


In [6]:
# complex number
x = tf.constant([[-2.25 + 4.75j], 
                 [-3.25 + 5.75j]])
x_abs = tf.abs(x)
print(x)
print(x_abs)



tf.Tensor(
[[-2.25+4.75j]
 [-3.25+5.75j]], shape=(2, 1), dtype=complex128)
tf.Tensor(
[[5.25594901]
 [6.60492241]], shape=(2, 1), dtype=float64)


In [7]:
x = tf.constant([4.0],)
x_abs = tf.math.abs(x)
print(x_abs)
print(tf.math.sqrt(x))

tf.Tensor([4.], shape=(1,), dtype=float32)
tf.Tensor([2.], shape=(1,), dtype=float32)


In [8]:
a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([10, 20, 30, 40, 50])

result = tf.math.add (a,b)
print("a + b = ",result)

result = tf.math.subtract (a,b)
print("a - b = ",result)

result = tf.math.multiply (a,b)
print("a * b = ",result)

result = tf.math.divide (a,b)
print("a / b = ",result)

a + b =  tf.Tensor([11 22 33 44 55], shape=(5,), dtype=int32)
a - b =  tf.Tensor([ -9 -18 -27 -36 -45], shape=(5,), dtype=int32)
a * b =  tf.Tensor([ 10  40  90 160 250], shape=(5,), dtype=int32)
a / b =  tf.Tensor([0.1 0.1 0.1 0.1 0.1], shape=(5,), dtype=float64)


In [9]:
tf.constant(3.0) / 0.0
tf.math.divide_no_nan(3.0, 0.0)


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [10]:
a = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
b = tf.constant([10, 20, 0, 40, 50], dtype=tf.float32)


print("In general , a / b = ", tf.math.divide(a,b))
print("Using divide_no_nan, a / b = ", tf.math.divide_no_nan(a,b))

In general , a / b =  tf.Tensor([0.1 0.1 inf 0.1 0.1], shape=(5,), dtype=float32)
Using divide_no_nan, a / b =  tf.Tensor([0.1 0.1 0.  0.1 0.1], shape=(5,), dtype=float32)


In [11]:
a = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
b = tf.constant([7], dtype=tf.float32)

print("a + b = ",tf.math.add(a,b))
print("a - b = ",tf.math.subtract(a,b))

a + b =  tf.Tensor([ 8.  9. 10. 11. 12.], shape=(5,), dtype=float32)
a - b =  tf.Tensor([-6. -5. -4. -3. -2.], shape=(5,), dtype=float32)


In [12]:
a = tf.constant([[1, 2, 3, 4, 5], [6,7,8,9,10]], dtype=tf.float32)
b = tf.constant([7], dtype=tf.float32)

print("a + b = ",tf.math.add(a,b))
print("a - b = ",tf.math.subtract(a,b))

a + b =  tf.Tensor(
[[ 8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17.]], shape=(2, 5), dtype=float32)
a - b =  tf.Tensor(
[[-6. -5. -4. -3. -2.]
 [-1.  0.  1.  2.  3.]], shape=(2, 5), dtype=float32)


In [13]:
a = tf.constant([[1, 2, 3, 4, 5], [6,7,8,9,10]], dtype=tf.float32)
b = tf.constant([[7], [5]], dtype=tf.float32)

print("a + b = ",tf.math.add(a,b))
print("a - b = ",tf.math.subtract(a,b))

a + b =  tf.Tensor(
[[ 8.  9. 10. 11. 12.]
 [11. 12. 13. 14. 15.]], shape=(2, 5), dtype=float32)
a - b =  tf.Tensor(
[[-6. -5. -4. -3. -2.]
 [ 1.  2.  3.  4.  5.]], shape=(2, 5), dtype=float32)


In [14]:
a = tf.constant([[1, 2, 3, 4, 5], [6,7,8,9,10]], dtype=tf.float32)
b = tf.constant([[7], [5]], dtype=tf.float32)

print("a + b = ",tf.math.multiply(a,b))
print("a - b = ",tf.math.multiply_no_nan(a,b))

a + b =  tf.Tensor(
[[ 7. 14. 21. 28. 35.]
 [30. 35. 40. 45. 50.]], shape=(2, 5), dtype=float32)
a - b =  tf.Tensor(
[[ 7. 14. 21. 28. 35.]
 [30. 35. 40. 45. 50.]], shape=(2, 5), dtype=float32)


In [15]:
a = tf.constant([[1, 2, 3, 4, 5]], dtype=tf.float32)
b = tf.constant([[7], [5], [3]], dtype=tf.float32)

result = tf.math.multiply(a,b)

print("a + b = ",tf.math.multiply(a,b))

print("shape of a is ", a.shape)
print("shape of b is ",b.shape)
print("shape of result is ",result.shape)




## Visulaie this as like

# 1, 2, 3, 4, 5               7 7 7 7 7            7. 14. 21. 28. 35.
# 1, 2, 3, 4, 5       *       5 5 5 5 5    =       5. 10. 15. 20. 25.
# 1, 2, 3, 4, 5               3 3 3 3 3            3.  6.  9. 12. 15.


a + b =  tf.Tensor(
[[ 7. 14. 21. 28. 35.]
 [ 5. 10. 15. 20. 25.]
 [ 3.  6.  9. 12. 15.]], shape=(3, 5), dtype=float32)
shape of a is  (1, 5)
shape of b is  (3, 1)
shape of result is  (3, 5)


    tf.math.argmin

In [16]:
# tf.math.minimum
a = tf.constant([1, 21, 3, 4, 55], dtype=tf.float32)
b = tf.constant([10, 14, 0, 40, 50], dtype=tf.float32)

tf.math.minimum(a,b)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1., 14.,  0.,  4., 50.], dtype=float32)>

    - tf.math.argmax (tensor, axis)


In [17]:
a = tf.constant([2,20,30,3,6])
print(tf.math.argmax(a))         # return the index of element where maximum element is present

tf.Tensor(2, shape=(), dtype=int64)


In [18]:
a = tf.constant([200,120,130,3,6])
print(tf.math.argmax(a))

tf.Tensor(0, shape=(), dtype=int64)


In [19]:
b = tf.constant(
    [[2,20,30,3,6],
    [3,11,16,1,8],
    [14,45,23,5,27]]
)

print(tf.math.argmax(b,axis = 0))       # axis =0 means in a column
print(tf.math.argmax(b,axis = 1))       # axis =1 means in a column

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [20]:
print(tf.math.argmin(b, axis=0))
print(tf.math.argmin(b, axis=1))

tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [21]:
c = tf.constant([
    [
       [1,5,7],
       [7,8,5] 
    ],
    [
       [1,5,8],
       [9,8,6] 
    ],
    [
       [1,3,7],
       [7,4,5] 
    ]   
])


print(c.shape) 
print(tf.math.argmax(c))        # defaukt axis is 0 i.e 
print(tf.math.argmax(c,axis = 0))
print(tf.math.argmax(c, axis= 1))

(3, 2, 3)
tf.Tensor(
[[0 0 1]
 [1 0 1]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[0 0 1]
 [1 0 1]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[1 1 0]
 [1 1 0]
 [1 1 0]], shape=(3, 3), dtype=int64)


In [22]:
image = tf.constant([[[0.1, 0.2, 0.9], [0.7, 0.4, 0.3]], [[0.5, 0.6, 0.2], [0.8, 0.1, 0.4]]])

image.shape

TensorShape([2, 2, 3])

In [23]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

    - tensor comparison

In [24]:
x = tf.constant([2, 4])
y = tf.constant([2])

tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [25]:
print(tf.math.equal(x,y))

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [26]:
y = tf.constant([2])
v = tf.constant(2)

In [27]:
print(y.shape)
print(v.shape)

(1,)
()


In [28]:
b = tf.constant(
    [[2,20,30,3,6],
    [3,11,16,1,8],
    [14,45,23,5,27]]
)

a = tf.constant([5])

print(tf.math.equal(b,a))

tf.Tensor(
[[False False False False False]
 [False False False False False]
 [False False False  True False]], shape=(3, 5), dtype=bool)


    - power function -> tf.pow()

In [29]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [30]:
x = tf.constant([
    [2,2],
    [3,3]
])

y = tf.constant([
    [3,0],
    [1,4]
])

tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]])>

In [31]:
print(tf.pow(x,y))

tf.Tensor(
[[ 8  1]
 [ 3 81]], shape=(2, 2), dtype=int32)


    - reduce functions

In [32]:
r1 = tf.constant([
    [1,3,4],
    [8,6,0],
    [30,12,5],
    [71,6,9]
])


print(r1)



tf.Tensor(
[[ 1  3  4]
 [ 8  6  0]
 [30 12  5]
 [71  6  9]], shape=(4, 3), dtype=int32)


In [33]:
print(tf.reduce_sum(r1))       # default it will sum to all values

tf.Tensor(155, shape=(), dtype=int32)


In [34]:
print(tf.reduce_sum(r1,axis = 0))      # column

tf.Tensor([110  27  18], shape=(3,), dtype=int32)


In [35]:
print(tf.reduce_sum(r1, axis = 1)) # row

tf.Tensor([ 8 14 47 86], shape=(4,), dtype=int32)


In [36]:
tf.reduce_min(r1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [37]:
print(tf.reduce_min(r1))
print(tf.reduce_max(r1))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(71, shape=(), dtype=int32)


In [38]:
print(tf.reduce_mean(r1))


tf.Tensor(12, shape=(), dtype=int32)


In [39]:
print(tf.reduce_sum(r1, axis=0))
print(tf.reduce_sum(r1, axis=1))

tf.Tensor([110  27  18], shape=(3,), dtype=int32)
tf.Tensor([ 8 14 47 86], shape=(4,), dtype=int32)


In [40]:
r2 = tf.constant([
    [1,3,4],
    [8,6,0],
    [30,12,5],
    [71,6,9]
],dtype = tf.float16)


print(r2)

tf.Tensor(
[[ 1.  3.  4.]
 [ 8.  6.  0.]
 [30. 12.  5.]
 [71.  6.  9.]], shape=(4, 3), dtype=float16)


In [41]:
print(tf.math.reduce_std(r2))
print(tf.math.reduce_std(r2,axis=0))
print(tf.math.reduce_std(r2, axis=1))

tf.Tensor(19.05, shape=(), dtype=float16)
tf.Tensor([27.3    3.27   3.201], shape=(3,), dtype=float16)
tf.Tensor([ 1.247  3.4   10.52  29.95 ], shape=(4,), dtype=float16)


    - tf sigmoid function

In [42]:
# x = tf.constant([1,3,4])
# tf.math.sigmoid(x)


# the above code will give an error bexause the sigmoid function is only valid for the float, doubl evalus 

# list of allowed values 
# DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128

In [43]:
x = tf.constant([1,3,4], dtype = tf.float16)
tf.math.sigmoid(x)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([0.731 , 0.9526, 0.982 ], dtype=float16)>

    - tf.math.top_k

In [44]:
print(tf.math.top_k(x))

TopKV2(values=<tf.Tensor: shape=(1,), dtype=float16, numpy=array([4.], dtype=float16)>, indices=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>)


In [45]:
# print(tf.math.top_k(x, k =5))

In [46]:
result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1], k = 3)
print(result)

TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([99, 98, 96])>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 9])>)


In [47]:
tensor = tf.constant([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1])
result = tf.math.top_k(tensor, k = tensor.shape[0])
print(result)



# reverse the tensor using top k method 

TopKV2(values=<tf.Tensor: shape=(12,), dtype=int32, numpy=array([99, 98, 96,  4,  3,  3,  2,  1,  1,  1,  1,  1])>, indices=<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 5,  2,  9, 10,  6,  8,  1,  0,  3,  4,  7, 11])>)


In [48]:
tensor.shape

TensorShape([12])

In [49]:
tensor.shape[0]

12

    - tf.linalg.matmul

#linalg --> stands for linear algebra 

In [50]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])

print("tensor a ")
print(a)
print("tensor b")
print(b)

tensor a 
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tensor b
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [51]:
c = tf.linalg.matmul(a,b)          # matmul stands for matrix multiplications

In [52]:
print(c)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [53]:
c = a@b
print(c)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


    -transpose of matrix

In [54]:
print("Original matrix")
print(a)

print("tranpose matric is ")
print(tf.transpose(a))

Original matrix
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tranpose matric is 
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [55]:
print(a.shape)
print(tf.transpose(a).shape)

(2, 3)
(3, 2)


In [56]:
x = tf.constant([1,2,0])
print("orininal matrix is ")
print(x)


print("Transpoded matrix")
print(tf.transpose(x))

orininal matrix is 
tf.Tensor([1 2 0], shape=(3,), dtype=int32)
Transpoded matrix
tf.Tensor([1 2 0], shape=(3,), dtype=int32)


In [57]:
x.shape

TensorShape([3])

In [58]:
x = tf.constant([[1],[2],[0]])
print("orininal matrix is ")
print(x)
tf.transpose(x)

print("Transpoded matrix")
print(x)

orininal matrix is 
tf.Tensor(
[[1]
 [2]
 [0]], shape=(3, 1), dtype=int32)
Transpoded matrix
tf.Tensor(
[[1]
 [2]
 [0]], shape=(3, 1), dtype=int32)


In [59]:
twoD = tf.constant(
    [[1,5,7],
    [7,8,5]]
)

In [60]:
print(twoD)

tf.Tensor(
[[1 5 7]
 [7 8 5]], shape=(2, 3), dtype=int32)


In [61]:
tf.transpose(twoD)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 7],
       [5, 8],
       [7, 5]])>

In [62]:
print(twoD)

tf.Tensor(
[[1 5 7]
 [7 8 5]], shape=(2, 3), dtype=int32)


In [63]:
mtx1 = tf.constant(
    [[1,5,7],
    [7,8,5]]
)

mtx2 = tf.constant(
    [[1,5],
    [7,8],
    [6,8]]
)

In [64]:
tf.linalg.matmul(mtx1,mtx2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 78, 101],
       [ 93, 139]])>

In [65]:
mtx1 @ mtx2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 78, 101],
       [ 93, 139]])>

In [66]:
tf.transpose(mtx1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 7],
       [5, 8],
       [7, 5]])>

In [67]:
tf.transpose(mtx2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 7, 6],
       [5, 8, 8]])>

In [68]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])

In [69]:
tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [70]:
tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=True,
    b_is_sparse=True,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [71]:
tf.linalg.adjoint(
    matrix, name=None
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])>

In [72]:
x = tf.constant([[1 + 1j, 2 + 2j, 3 + 3j],
                 [4 + 4j, 5 + 5j, 6 + 6j]])

In [73]:
tf.linalg.adjoint(x)

<tf.Tensor: shape=(3, 2), dtype=complex128, numpy=
array([[1.-1.j, 4.-4.j],
       [2.-2.j, 5.-5.j],
       [3.-3.j, 6.-6.j]])>

    - tf.linalg.band_part() function
        - refere tf-bend_part.pff in drive

In [76]:
input = tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8]
], dtype = tf.float16
)

In [77]:
tf.linalg.band_part(input,0,0)     # keep the diagonal values only

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [79]:
tf.linalg.band_part(input,-1,0) # keep the lower triangular value 

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [3., 5., 0.],
       [1., 5., 6.],
       [2., 3., 8.]], dtype=float16)>

In [80]:
tf.linalg.band_part(input, 0, -1) # keep the upper triangular values

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [ ]:
# be aware of the following functions 
# for matrix cross product => tf.linalg.cross(tensor1, tensor2)

# for cholesky matrix  => tf.linalg.cholesky(tensor)

# to find determinant value of any tensor => tf.linalg.det(tensor)

# to find inverse of given matrix / tensor => tf.linalg.inv(input)

# Note: to find inverse of matrix the matrix should be square matrix if the input matrix is not square matrix then we get run error 

# 


In [83]:
input = tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8]
]
)

In [85]:
# tf.linalg.inv(input)   # error saying tensor dtype must be in [DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]

In [86]:
# we can solve the error by using appropriate data type as shown 
input = tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8]
], dtype = tf.float32
)

In [89]:
# tf.linalg.inv(input)     # this time we get error saying Input matrix must be square

In [90]:
# we can solve the error by using square matrix of appropriate data type
input = tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6],
], dtype = tf.float32
)

In [92]:
inverse_of_input = tf.linalg.inv(input)      # error free
print(inverse_of_input)

tf.Tensor(
[[ 0.7413249  -0.01892742  0.3154574 ]
 [-0.12933755 -0.00946371  0.1577287 ]
 [-0.01577287  0.01104101 -0.01735016]], shape=(3, 3), dtype=float32)


In [96]:
input @ inverse_of_input     # = identity matrix of shaoe 3 x 3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  7.4505806e-09,  0.0000000e+00],
       [ 1.6391277e-07,  1.0000000e+00,  1.6391277e-07],
       [-5.2154064e-08,  7.4505806e-08,  1.0000000e+00]], dtype=float32)>

In [ ]:
# for matrix transpose using tf.linalg => tf.linalg.matrix_transpose
# for matrix trace value using tf.linalg => tf.linalg.trace

In [98]:
tf.linalg.matrix_transpose(input)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[  1.,   3.,   1.],
       [ -2.,   5.,   5.],
       [  0., 100.,   6.]], dtype=float32)>

In [97]:
tf.linalg.trace(input)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [99]:
# singular value decompositions
tf.linalg.svd(input)

# returns three matrix s , u , and v 

# s => 
# u => left singular matrix
# v =>right singular matrix

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100.3663   ,   5.1059036,   1.2371687], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-7.4980810e-04, -3.7569830e-01,  9.2674178e-01],
        [ 9.9803799e-01, -5.8300879e-02, -2.2827482e-02],
        [ 6.2606096e-02,  9.2490643e-01,  3.7500489e-01]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.03044816,  0.07330841,  0.99684453],
        [ 0.0528536 ,  0.9957936 , -0.07484547],
        [ 0.998138  , -0.05496572, -0.02644547]], dtype=float32)>)

In [100]:
s,u,v = tf.linalg.svd(input)

In [101]:
print(s)
print(u)
print(v)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03044816  0.07330841  0.99684453]
 [ 0.0528536   0.9957936  -0.07484547]
 [ 0.998138   -0.05496572 -0.02644547]], shape=(3, 3), dtype=float32)


In [102]:
# numpy array matrix multiplications
import numpy as np 

a = np.array([[1, 0],
              [0, 1]])

b = np.array([1, 2])

In [103]:
np.matmul(a,b)

array([1, 2])

In [104]:
np.einsum(a,b)

array([[1, 0],
       [0, 1]])

In [105]:
a@b

array([1, 2])