In [2]:
import tensorflow as tf

In [5]:
x = tf.constant([5, -4 , 6])

In [8]:
abs_x = tf.math.abs(x)
print(abs_x)

tf.Tensor([5 4 6], shape=(3,), dtype=int32)


In [10]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
x_abs = tf.abs(x)
print(x)
print(x_abs)



tf.Tensor(
[[-2.25+4.75j]
 [-3.25+5.75j]], shape=(2, 1), dtype=complex128)
tf.Tensor(
[[5.25594901]
 [6.60492241]], shape=(2, 1), dtype=float64)


In [17]:
x = tf.constant([4.0],)
x_abs = tf.math.abs(x)
print(tf.math.sqrt(x))

tf.Tensor([2.], shape=(1,), dtype=float32)


In [20]:
a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([10, 20, 30, 40, 50])

result = tf.math.add (a,b)
print("a + b = ",result)

result = tf.math.subtract (a,b)
print("a - b = ",result)

result = tf.math.multiply (a,b)
print("a * b = ",result)

result = tf.math.divide (a,b)
print("a / b = ",result)

a + b =  tf.Tensor([11 22 33 44 55], shape=(5,), dtype=int32)
a - b =  tf.Tensor([ -9 -18 -27 -36 -45], shape=(5,), dtype=int32)
a * b =  tf.Tensor([ 10  40  90 160 250], shape=(5,), dtype=int32)
a / b =  tf.Tensor([0.1 0.1 0.1 0.1 0.1], shape=(5,), dtype=float64)


In [21]:
tf.constant(3.0) / 0.0
tf.math.divide_no_nan(3.0, 0.0)


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [27]:
a = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
b = tf.constant([10, 20, 0, 40, 50], dtype=tf.float32)


print("In general , a / b = ", tf.math.divide(a,b))
print("Using divide_no_nan, a / b = ", tf.math.divide_no_nan(a,b))

In general , a / b =  tf.Tensor([0.1 0.1 inf 0.1 0.1], shape=(5,), dtype=float32)
Using divide_no_nan, a / b =  tf.Tensor([0.1 0.1 0.  0.1 0.1], shape=(5,), dtype=float32)


In [28]:
a = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
b = tf.constant([7], dtype=tf.float32)

print("a + b = ",tf.math.add(a,b))
print("a - b = ",tf.math.subtract(a,b))

a + b =  tf.Tensor([ 8.  9. 10. 11. 12.], shape=(5,), dtype=float32)
a - b =  tf.Tensor([-6. -5. -4. -3. -2.], shape=(5,), dtype=float32)
