In [2]:
a = 5

In [3]:
import tensorflow as tf

In [4]:
x = tf.constant([5, -4 , 6])

In [5]:
abs_x = tf.math.abs(x)
print(abs_x)

tf.Tensor([5 4 6], shape=(3,), dtype=int32)


In [6]:
# complex number
x = tf.constant([[-2.25 + 4.75j], 
                 [-3.25 + 5.75j]])
x_abs = tf.abs(x)
print(x)
print(x_abs)



tf.Tensor(
[[-2.25+4.75j]
 [-3.25+5.75j]], shape=(2, 1), dtype=complex128)
tf.Tensor(
[[5.25594901]
 [6.60492241]], shape=(2, 1), dtype=float64)


In [7]:
x = tf.constant([4.0],)
x_abs = tf.math.abs(x)
print(x_abs)
print(tf.math.sqrt(x))

tf.Tensor([4.], shape=(1,), dtype=float32)
tf.Tensor([2.], shape=(1,), dtype=float32)


In [8]:
a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([10, 20, 30, 40, 50])

result = tf.math.add (a,b)
print("a + b = ",result)

result = tf.math.subtract (a,b)
print("a - b = ",result)

result = tf.math.multiply (a,b)
print("a * b = ",result)

result = tf.math.divide (a,b)
print("a / b = ",result)

a + b =  tf.Tensor([11 22 33 44 55], shape=(5,), dtype=int32)
a - b =  tf.Tensor([ -9 -18 -27 -36 -45], shape=(5,), dtype=int32)
a * b =  tf.Tensor([ 10  40  90 160 250], shape=(5,), dtype=int32)
a / b =  tf.Tensor([0.1 0.1 0.1 0.1 0.1], shape=(5,), dtype=float64)


In [9]:
tf.constant(3.0) / 0.0
tf.math.divide_no_nan(3.0, 0.0)


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [10]:
a = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
b = tf.constant([10, 20, 0, 40, 50], dtype=tf.float32)


print("In general , a / b = ", tf.math.divide(a,b))
print("Using divide_no_nan, a / b = ", tf.math.divide_no_nan(a,b))

In general , a / b =  tf.Tensor([0.1 0.1 inf 0.1 0.1], shape=(5,), dtype=float32)
Using divide_no_nan, a / b =  tf.Tensor([0.1 0.1 0.  0.1 0.1], shape=(5,), dtype=float32)


In [11]:
a = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
b = tf.constant([7], dtype=tf.float32)

print("a + b = ",tf.math.add(a,b))
print("a - b = ",tf.math.subtract(a,b))

a + b =  tf.Tensor([ 8.  9. 10. 11. 12.], shape=(5,), dtype=float32)
a - b =  tf.Tensor([-6. -5. -4. -3. -2.], shape=(5,), dtype=float32)


In [12]:
a = tf.constant([[1, 2, 3, 4, 5], [6,7,8,9,10]], dtype=tf.float32)
b = tf.constant([7], dtype=tf.float32)

print("a + b = ",tf.math.add(a,b))
print("a - b = ",tf.math.subtract(a,b))

a + b =  tf.Tensor(
[[ 8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17.]], shape=(2, 5), dtype=float32)
a - b =  tf.Tensor(
[[-6. -5. -4. -3. -2.]
 [-1.  0.  1.  2.  3.]], shape=(2, 5), dtype=float32)


In [13]:
a = tf.constant([[1, 2, 3, 4, 5], [6,7,8,9,10]], dtype=tf.float32)
b = tf.constant([[7], [5]], dtype=tf.float32)

print("a + b = ",tf.math.add(a,b))
print("a - b = ",tf.math.subtract(a,b))

a + b =  tf.Tensor(
[[ 8.  9. 10. 11. 12.]
 [11. 12. 13. 14. 15.]], shape=(2, 5), dtype=float32)
a - b =  tf.Tensor(
[[-6. -5. -4. -3. -2.]
 [ 1.  2.  3.  4.  5.]], shape=(2, 5), dtype=float32)


In [14]:
a = tf.constant([[1, 2, 3, 4, 5], [6,7,8,9,10]], dtype=tf.float32)
b = tf.constant([[7], [5]], dtype=tf.float32)

print("a + b = ",tf.math.multiply(a,b))
print("a - b = ",tf.math.multiply_no_nan(a,b))

a + b =  tf.Tensor(
[[ 7. 14. 21. 28. 35.]
 [30. 35. 40. 45. 50.]], shape=(2, 5), dtype=float32)
a - b =  tf.Tensor(
[[ 7. 14. 21. 28. 35.]
 [30. 35. 40. 45. 50.]], shape=(2, 5), dtype=float32)


In [15]:
a = tf.constant([[1, 2, 3, 4, 5]], dtype=tf.float32)
b = tf.constant([[7], [5], [3]], dtype=tf.float32)

result = tf.math.multiply(a,b)

print("a + b = ",tf.math.multiply(a,b))

print("shape of a is ", a.shape)
print("shape of b is ",b.shape)
print("shape of result is ",result.shape)




## Visulaie this as like

# 1, 2, 3, 4, 5               7 7 7 7 7            7. 14. 21. 28. 35.
# 1, 2, 3, 4, 5       *       5 5 5 5 5    =       5. 10. 15. 20. 25.
# 1, 2, 3, 4, 5               3 3 3 3 3            3.  6.  9. 12. 15.


a + b =  tf.Tensor(
[[ 7. 14. 21. 28. 35.]
 [ 5. 10. 15. 20. 25.]
 [ 3.  6.  9. 12. 15.]], shape=(3, 5), dtype=float32)
shape of a is  (1, 5)
shape of b is  (3, 1)
shape of result is  (3, 5)


    tf.math.argmin

In [16]:
# tf.math.minimum
a = tf.constant([1, 21, 3, 4, 55], dtype=tf.float32)
b = tf.constant([10, 14, 0, 40, 50], dtype=tf.float32)

tf.math.minimum(a,b)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1., 14.,  0.,  4., 50.], dtype=float32)>

    - tf.math.argmax (tensor, axis)


In [18]:
a = tf.constant([2,20,30,3,6])
print(tf.math.argmax(a))         # return the index of element where maximum element is present

tf.Tensor(2, shape=(), dtype=int64)


In [19]:
a = tf.constant([200,120,130,3,6])
print(tf.math.argmax(a))

tf.Tensor(0, shape=(), dtype=int64)


In [23]:
b = tf.constant(
    [[2,20,30,3,6],
    [3,11,16,1,8],
    [14,45,23,5,27]]
)

print(tf.math.argmax(b,axis = 0))       # axis =0 means in a column
print(tf.math.argmax(b,axis = 1))       # axis =1 means in a column

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [24]:
print(tf.math.argmin(b, axis=0))
print(tf.math.argmin(b, axis=1))

tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [32]:
c = tf.constant([
    [
       [1,5,7],
       [7,8,5] 
    ],
    [
       [1,5,8],
       [9,8,6] 
    ],
    [
       [1,3,7],
       [7,4,5] 
    ]   
])


print(c.shape) 
print(tf.math.argmax(c))        # defaukt axis is 0 i.e 
print(tf.math.argmax(c,axis = 0))
print(tf.math.argmax(c, axis= 1))

(3, 2, 3)
tf.Tensor(
[[0 0 1]
 [1 0 1]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[0 0 1]
 [1 0 1]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[1 1 0]
 [1 1 0]
 [1 1 0]], shape=(3, 3), dtype=int64)


In [33]:
image = tf.constant([[[0.1, 0.2, 0.9], [0.7, 0.4, 0.3]], [[0.5, 0.6, 0.2], [0.8, 0.1, 0.4]]])

image.shape

TensorShape([2, 2, 3])

In [31]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

    - tensor comparison

In [36]:
x = tf.constant([2, 4])
y = tf.constant([2])

tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [37]:
print(tf.math.equal(x,y))

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [38]:
y = tf.constant([2])
v = tf.constant(2)

TensorShape([1])

In [40]:
print(y.shape)
print(v.shape)

(1,)
()


In [43]:
b = tf.constant(
    [[2,20,30,3,6],
    [3,11,16,1,8],
    [14,45,23,5,27]]
)

a = tf.constant([5])

print(tf.math.equal(b,a))

tf.Tensor(
[[False False False False False]
 [False False False False False]
 [False False False  True False]], shape=(3, 5), dtype=bool)


    - power function -> tf.pow()

In [46]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [44]:
x = tf.constant([
    [2,2],
    [3,3]
])

y = tf.constant([
    [3,0],
    [1,4]
])

tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]])>

In [45]:
print(tf.pow(x,y))

tf.Tensor(
[[ 8  1]
 [ 3 81]], shape=(2, 2), dtype=int32)


    - reduce functions

In [62]:
r1 = tf.constant([
    [1,3,4],
    [8,6,0],
    [30,12,5],
    [71,6,9]
])


print(r1)



tf.Tensor(
[[ 1  3  4]
 [ 8  6  0]
 [30 12  5]
 [71  6  9]], shape=(4, 3), dtype=int32)


In [51]:
print(tf.reduce_sum(r1))       # default it will sum to all values

tf.Tensor(155, shape=(), dtype=int32)


In [52]:
print(tf.reduce_sum(r1,axis = 0))      # column

tf.Tensor([110  27  18], shape=(3,), dtype=int32)


In [53]:
print(tf.reduce_sum(r1, axis = 1)) # row

tf.Tensor([ 8 14 47 86], shape=(4,), dtype=int32)


In [54]:
tf.reduce_min(r1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [56]:
print(tf.reduce_min(r1))
print(tf.reduce_max(r1))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(71, shape=(), dtype=int32)


In [59]:
print(tf.reduce_mean(r1))


tf.Tensor(12, shape=(), dtype=int32)


In [60]:
print(tf.reduce_sum(r1, axis=0))
print(tf.reduce_sum(r1, axis=1))

tf.Tensor([110  27  18], shape=(3,), dtype=int32)
tf.Tensor([ 8 14 47 86], shape=(4,), dtype=int32)


In [63]:
r2 = tf.constant([
    [1,3,4],
    [8,6,0],
    [30,12,5],
    [71,6,9]
],dtype = tf.float16)


print(r2)

tf.Tensor(
[[ 1.  3.  4.]
 [ 8.  6.  0.]
 [30. 12.  5.]
 [71.  6.  9.]], shape=(4, 3), dtype=float16)


In [64]:
print(tf.math.reduce_std(r2))
print(tf.math.reduce_std(r2,axis=0))
print(tf.math.reduce_std(r2, axis=1))

tf.Tensor(19.05, shape=(), dtype=float16)
tf.Tensor([27.3    3.27   3.201], shape=(3,), dtype=float16)
tf.Tensor([ 1.247  3.4   10.52  29.95 ], shape=(4,), dtype=float16)


    - tf sigmoid function

In [68]:
# x = tf.constant([1,3,4])
# tf.math.sigmoid(x)


# the above code will give an error bexause the sigmoid function is only valid for the float, doubl evalus 

# list of allowed values 
# DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128

In [69]:
x = tf.constant([1,3,4], dtype = tf.float16)
tf.math.sigmoid(x)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([0.731 , 0.9526, 0.982 ], dtype=float16)>

    - tf.math.top_k

In [71]:
print(tf.math.top_k(x))

TopKV2(values=<tf.Tensor: shape=(1,), dtype=float16, numpy=array([4.], dtype=float16)>, indices=<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>)


In [73]:
# print(tf.math.top_k(x, k =5))

In [75]:
result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1], k = 3)
print(result)

TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([99, 98, 96])>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 9])>)


In [87]:
tensor = tf.constant([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1])
result = tf.math.top_k(tensor, k = tensor.shape[0])
print(result)



# reverse the tensor using top k method 

TopKV2(values=<tf.Tensor: shape=(12,), dtype=int32, numpy=array([99, 98, 96,  4,  3,  3,  2,  1,  1,  1,  1,  1])>, indices=<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 5,  2,  9, 10,  6,  8,  1,  0,  3,  4,  7, 11])>)


In [88]:
tensor.shape

TensorShape([12])

In [89]:
tensor.shape[0]

12

    - tf.linalg.matmul

#linalg --> stands for linear algebra 

In [90]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])

print("tensor a ")
print(a)
print("tensor b")
print(b)

tensor a 
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tensor b
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


In [93]:
c = tf.linalg.matmul(a,b)          # matmul stands for matrix multiplications

In [94]:
print(c)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [95]:
c = a@b
print(c)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


    -transpose of matrix

In [99]:
print("Original matrix")
print(a)

print("tranpose matric is ")
print(tf.transpose(a))

Original matrix
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tranpose matric is 
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [101]:
print(a.shape)
print(tf.transpose(a).shape)

(2, 3)
(3, 2)


In [104]:
x = tf.constant([1,2,0])
print("orininal matrix is ")
print(x)


print("Transpoded matrix")
print(tf.transpose(x))

orininal matrix is 
tf.Tensor([1 2 0], shape=(3,), dtype=int32)
Transpoded matrix
tf.Tensor([1 2 0], shape=(3,), dtype=int32)


In [105]:
x.shape

TensorShape([3])

In [106]:
x = tf.constant([[1],[2],[0]])
print("orininal matrix is ")
print(x)
tf.transpose(x)

print("Transpoded matrix")
print(x)

orininal matrix is 
tf.Tensor(
[[1]
 [2]
 [0]], shape=(3, 1), dtype=int32)
Transpoded matrix
tf.Tensor(
[[1]
 [2]
 [0]], shape=(3, 1), dtype=int32)


In [108]:
twoD = tf.constant(
    [[1,5,7],
    [7,8,5]]
)

In [109]:
print(twoD)

tf.Tensor(
[[1 5 7]
 [7 8 5]], shape=(2, 3), dtype=int32)


In [110]:
tf.transpose(twoD)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 7],
       [5, 8],
       [7, 5]])>

In [111]:
print(twoD)

tf.Tensor(
[[1 5 7]
 [7 8 5]], shape=(2, 3), dtype=int32)


In [113]:
mtx1 = tf.constant(
    [[1,5,7],
    [7,8,5]]
)

mtx2 = tf.constant(
    [[1,5],
    [7,8],
    [6,8]]
)

In [114]:
tf.linalg.matmul(mtx1,mtx2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 78, 101],
       [ 93, 139]])>

In [115]:
mtx1 @ mtx2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 78, 101],
       [ 93, 139]])>

In [116]:
tf.transpose(mtx1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 7],
       [5, 8],
       [7, 5]])>

In [117]:
tf.transpose(mtx2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 7, 6],
       [5, 8, 8]])>