In [1]:
import numpy as np

In [6]:
x = np.array([[1, 2], [3, 4]])
x


array([[1, 2],
       [3, 4]])

In [10]:
v = np.array([1, 2]).reshape((2, 1))
v


array([[1],
       [2]])

In [12]:
v = np.array([1, 2])
v

array([1, 2])

In [13]:
np.dot(x,v)

array([ 5, 11])

In [14]:
x * v 

array([[1, 4],
       [3, 8]])

In [15]:
np.dot(v, x)

array([ 7, 10])

In [16]:
import scipy

In [20]:
import scipy.linalg
scipy.linalg.svd(x, full_matrices=False)


(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))