https://www.w3schools.com/python/numpy/default.asp

## Numpy
    NumPy is short for "Numerical Python".

1. numpy is the low level library written in C and fortran for high level mathematical functions
2. numpy cleverly overcomes the problem of running slower algorithms on python by using multidimensional arrays and functions that operates on array
3. any algorithm can then be expressed as a function on arrays, allowing the algorithm to be run quickly
4. syntax is from python (easy to learn), performance is from c(best memory management).

## Aplications of Numpy
1. A powerful N-dimensional array object
2. Sophisticated (broadcasting) function
3. tools for integrating c/c++ and fortran code.
4. useful linear algebra, fourier transform, and random number capabilities

    numpy has only one data structure which is n dimensional aarray whereas python has 9 data structures

    most of the operations of numpy is supportive for number (integers, float, complex) only, and not for boolean and strings (actually it can hold strings but not have much application in ml part)

Note: Data Science is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

### Creating numpy arrays

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

#Get the data type of an array object:
print(arr.dtype)   # best way and recommended to use

#or 
print(type(arr[0]))

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32
<class 'numpy.int32'>


In [ ]:
# 0D -> 2
# 1d -> []
# 2d -> [ [], [] ]
# 3d -> [ [ []], [ []], [ []]]

In [3]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [4]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Accessing elemnets of numpy array

In [5]:
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [7]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### Slicing arrays

1. Slicing in python means taking elements from one given index to another given index.

2. We pass slice instead of index like this: [start:end].

3. We can also define the step, like this: [start:end:step].

4. If we don't pass start its considered 0

5. If we don't pass end its considered length of array in that dimension

6. If we don't pass step its considered 1

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
#               0  1  2  3  4  5  6
print(arr[1:5])

[2 3 4 5]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#                        -3  -2  -1
print(arr[-3:-1])

[5 6]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [15]:
# keyword used in coding problems 
# Return every other element from the entire array
# means show each alternative elements 
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

# to start with 2nd element 
print(arr[1::2])

[1 3 5 7]
[2 4 6]


In [16]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [17]:
# From both array , return index 2 elements
print(arr[0:2, 1])

[2 7]


In [18]:
#From both elements, slice index 1 to index 4 (not included)
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [19]:
#Get the data type of an array object:

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


## Data Types in arrays

In [21]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [22]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [24]:
arr = np.array([1, 2, 3, 4], dtype='i4')  # or can only write i
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [26]:
#A non integer string like 'a' can not be converted to integer (will raise an error):
# arr = np.array(['a', '2', '3'], dtype='i')
# error: ValueError: invalid literal for int() with base 10: 'a

In [28]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
# newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [29]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
