## copy function 

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
x[1] = 50

print('original array:', arr)
print('copied array with some changes', x)

original array: [42  2  3  4  5]
copied array with some changes [ 1 50  3  4  5]


## view function

In [4]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [5]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
x[1] = 50

print('original array:', arr)
print('view array with some changes', x)

original array: [42 50  3  4  5]
view array with some changes [42 50  3  4  5]


## Difference between copy() and view() functions 
https://www.w3schools.com/python/numpy/numpy_copy_vs_view.asp

In [7]:
# to check - 
# Print the value of the base attribute to check if an array owns it's data or not:

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy() # x owns the data
y = arr.view() # y uses arr data only 

print(x.base)   # give none means it dont have any base reference
print(y.base)   # print the original base reference array 

None
[1 2 3 4 5]


In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
# Use a correct NumPy method to change the shape of an array from 2-D to 1-D.
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
newarr = arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [15]:
# check this reshaping returns an copy or view 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 4)
print(newarr.base)   
print(newarr)

# ans: gives view 
# The example above returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


## Unknown dimension

In [ ]:
# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Iteration in numpy array
https://www.w3schools.com/python/numpy/numpy_array_iterating.asp

In [17]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [20]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [22]:
# np.nditer(arr) function 
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [23]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


## ndenumerate()

In [24]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [25]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## array joins

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [33]:
arr1 = np.array([ [1, 2],
                  [3, 4]
                ])

arr2 = np.array([[5, 6],
                  [7, 8]
                ])

arr = np.concatenate((arr1, arr2))
print(arr)

print('axis = 1')
narr = np.concatenate((arr1, arr2), axis = 1)
print(narr)

print('axis = 0')
narr = np.concatenate((arr1, arr2), axis = 0)
print(narr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
axis = 1
[[1 2 5 6]
 [3 4 7 8]]
axis = 0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)   # default value of axis is 0
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [35]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)   
print(arr)

[[1 2 3]
 [4 5 6]]


In [36]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2)) 
print(arr)

[[1 2 3]
 [4 5 6]]


In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))   # it dont have axis argument
print(arr)

[1 2 3 4 5 6]


In [40]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))   # it dont have axis argument
print(arr)

[[1 2 3]
 [4 5 6]]


In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Spliting the array

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6])
narr = np.array_split(arr, 3)

print(narr)

[array([1, 2]), array([3, 4]), array([5])]


In [44]:
arr = np.array([1, 2, 3, 4, 5])
narr = np.array_split(arr, 3)

print(narr)

[array([1, 2]), array([3, 4]), array([5])]


In [45]:
arr2 = np.array_split(arr, 4)
print(arr2)

[array([1, 2]), array([3]), array([4]), array([5])]


    - Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [49]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print("the shape of the array is : ",arr.shape)
print("the dimensions of the array is: ",arr.ndim)

narr = np.array_split(arr, 3)
print('the splited arrays are: \n',narr)

the shape of the array is :  (6, 2)
the dimensions of the array is:  2
the splited arrays are: 
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print("the shape of the array is : ",arr.shape)
print("the dimensions of the array is: ",arr.ndim)

narr = np.array_split(arr, 3)
print('the splited arrays are: \n',narr)

the shape of the array is :  (6, 3)
the dimensions of the array is:  2
the splited arrays are: 
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


## NumPy Searching Arrays

In [52]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
print(type(x))

(array([3, 5, 6], dtype=int64),)
<class 'tuple'>


In [53]:
#Find the indexes where the values are even
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


## use binary search
    The searchsorted() method is assumed to be used on sorted arrays.

In [54]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)  # since we are not specified the side value hence we are geting value from left side 
print(x)

1


In [56]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')   # 

print(x)

1


In [57]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


## NumPy Sorting Arrays

In [58]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


[0 1 2 3]


In [59]:
arr = np.array([3, 2, 0, 1])

sorted_arr = np.sort(arr)
print('original array: ', arr)
print('sorted array: ', sorted_arr)

original array:  [3 2 0 1]
sorted array:  [0 1 2 3]


In [60]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [61]:
arr = np.array([True, False, True])

print(np.sort(arr))
# assume false 0, true 1

[False  True  True]


## Self learn - Numpy array filtration 
https://www.w3schools.com/python/numpy/numpy_array_filter.asp